name: Build Nuga app

on:
  push:
    # tags:
    #   - v*
  workflow_dispatch:
  pull_request:

jobs:
  linux:
    name: Build Nuga AppImage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: app/go.sum
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - name: Install C/C++ deps
        run: sudo apt install libudev-dev libwebkit2gtk-4.0-dev libgtk-3-dev -y
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.5.1
      - name: Install frontend deps
        run: |
          cd app/frontend
          pnpm install --frozen-lockfile
          cd ../..
      - name: Sync workspace
        run: go work sync
      - name: Build x86_64 binary
        run: make build/linux
      - name: Build aarch64 binary
        run: make linux-builder/release/arm64
      - name: Build AppImages
        run: make linux-builder/appimage
