name: Quality assurance

on: [push, workflow_dispatch]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2
      - name: Install frontend deps
        run: |
          cd app/frontend
          pnpm install --frozen-lockfile
          cd ../..
      - name: Sync workspace
        run: go work sync
      - name: golangci-lint lib
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./lib
          skip-cache: true
      - name: revive lib
        uses: docker://morphy/revive-action:v2
        with:
          config: revive.toml
          path: "./lib/..."
      - name: golangci-lint app
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./app
          skip-cache: true
      - name: revive app
        uses: docker://morphy/revive-action:v2
        with:
          config: revive.toml
          path: "./app/..."
      - name: ESLint
        run: |
          cd app/frontend
          pnpm run lint:scripts
      - name: stylelint
        run: |
          cd app/frontend
          pnpm run lint:styles
