name: Release Nuga

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  linux:
    name: Build Nuga.AppImage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: app/go.sum
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: |
              cwd: app/frontend/
              args: [--frozen-lockfile]
          version: 8.6.2
      - name: Setup builder
        run: docker pull mishamyrt/nuga-linux-builder:latest-arm64
      - name: Setup native deps
        run: sudo apt install libudev-dev libwebkit2gtk-4.0-dev libgtk-3-dev -y
      - name: Setup Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.5.1
      - name: Sync workspace
        run: go work sync
      - name: Build x86_64 binary
        run: make build/linux
      - name: Build aarch64 binary
        run: make linux-builder/binary-arm64
      - name: Build AppImages
        run: make linux-builder/appimage
      - name: Upload AppImages
        uses: actions/upload-artifact@v3
        with:
          name: linux-dist
          path: ./dist
  mac:
    name: Build Nuga.app
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: app/go.sum
      - name: Setup native deps
        run: brew install hidapi
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: |
              cwd: app/frontend/
              args: [--frozen-lockfile]
          version: 8.6.2
      - name: Setup Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.5.1
      - name: Sync workspace
        run: go work sync
      - name: Build applications
        run: make build/darwin
      - name: Upload applications
        uses: actions/upload-artifact@v3
        with:
          name: mac-dist
          path: ./dist

